package builder

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/scaleapi/bodega/internal/manifest"
)

// FetchPypi resolves base requirements from previously-cloned git repos,
// combines them with the extra packages listed in pypi.json, and writes
// <build-root>/combined-requirements.txt.
//
// Before resolving requirements, FetchPypi auto-fetches and auto-packages any
// git repos referenced in base_requirements that have not yet been cloned. This
// eliminates the need for callers to manually sequence git and pypi fetches.
func FetchPypi(cfg *Config, store *manifest.Store) *Summary {
	out := cfg.stdout()
	summary := &Summary{}
	dirs := buildDirs(cfg.rootFor(manifest.TypePypi))

	if store.Pypi.Frozen {
		_, _ = fmt.Fprintf(out, "  [pypi] SKIPPED (frozen)\n")
		return summary
	}

	start := time.Now()
	result := Result{Type: manifest.TypePypi, Name: "requirements"}

	combinedReq := filepath.Join(cfg.rootFor(manifest.TypePypi), "combined-requirements.txt")
	_, _ = fmt.Fprintf(out, "\n>>> [pypi] fetch — resolving requirements\n")

	// Git repos referenced in base_requirements must be fetched before pypi.
	// The build order (binary → git → apt → pypi) ensures this.
	// If a git repo is missing, we fail with a clear error.

	reqLines := []string{"# Auto-generated by bodega from manifests/pypi.json\n"}

	for repoName, ref := range store.Pypi.BaseRequirements {
		worktree, err := GitWorktreePath(cfg.rootFor(manifest.TypeGit), repoName, ref)
		if err != nil {
			result.Err = fmt.Errorf("git worktree for %s@%s: %w", repoName, ref, err)
			summary.Failures++
			summary.Results = append(summary.Results, result)
			summary.Total++
			return summary
		}
		if worktree == "" {
			result.Err = fmt.Errorf(
				"git repo %q not found at %s — run 'fetch git' first",
				repoName, filepath.Join(dirs.repos, repoName+".git"),
			)
			summary.Failures++
			summary.Results = append(summary.Results, result)
			summary.Total++
			return summary
		}
		reqPath := filepath.Join(worktree, "requirements.txt")
		if _, err := os.Stat(reqPath); os.IsNotExist(err) {
			result.Err = fmt.Errorf("requirements.txt not found in %s", worktree)
			summary.Failures++
			summary.Results = append(summary.Results, result)
			summary.Total++
			return summary
		}
		_, _ = fmt.Fprintf(out, "    Base: %s @ %s (%s)\n", repoName, ref, reqPath)
		reqLines = append(reqLines, fmt.Sprintf("-r %s\n", reqPath))
	}

	_, _ = fmt.Fprintf(out, "    Extra packages: %d\n", len(store.Pypi.Packages))
	reqLines = append(reqLines, "\n# Extra packages from manifest\n")
	for _, pkg := range store.Pypi.Packages {
		_, _ = fmt.Fprintf(out, "      %s\n", pkg.Name)
		reqLines = append(reqLines, pkg.Name+"\n")
	}

	// Write combined requirements file.
	content := ""
	for _, line := range reqLines {
		content += line
	}
	if err := os.WriteFile(combinedReq, []byte(content), 0o644); err != nil {
		result.Err = fmt.Errorf("write combined requirements: %w", err)
		summary.Failures++
		summary.Results = append(summary.Results, result)
		summary.Total++
		return summary
	}
	_, _ = fmt.Fprintf(out, "    Requirements written to: %s\n", combinedReq)

	result.Artifacts = []string{combinedReq}
	result.Elapsed = time.Since(start)
	summary.Results = append(summary.Results, result)
	summary.Total++
	_, _ = fmt.Fprintf(out, "    Done (%s)\n", result.Elapsed.Round(time.Millisecond))

	if cfg.Logger != nil {
		cfg.Logger.Audit("OK      pypi/requirements  (%s)", result.Elapsed.Round(time.Millisecond))
	}

	return summary
}

// pypiWheelsDir returns the local wheels directory for a PypiManifest.
// When the manifest has a Version set, wheels land in wheels/<version>/ so
// that multiple wheel sets can coexist. Falls back to wheels/ when empty.
func pypiWheelsDir(d dirs, pypi manifest.PypiManifest) string {
	if pypi.Version != "" {
		return filepath.Join(d.wheels, pypi.Version)
	}
	return d.wheels
}

// pypiS3Prefix returns the S3 key prefix for pypi wheels.
// When the manifest has a Version set, the prefix includes the version:
// pypi/wheels/<version>/. Falls back to pypi/wheels/ when empty.
func pypiS3Prefix(pypi manifest.PypiManifest) string {
	if pypi.Version != "" {
		return "pypi/wheels/" + pypi.Version + "/"
	}
	return "pypi/wheels/"
}

// CheckPypiStage inspects the filesystem to determine which pipeline stages
// have completed for the pypi manifest.
func CheckPypiStage(cfg *Config, store *manifest.Store) StageStatus {
	d := buildDirs(cfg.rootFor(manifest.TypePypi))
	var s StageStatus

	// Fetched = combined-requirements.txt exists.
	combinedReq := filepath.Join(cfg.rootFor(manifest.TypePypi), "combined-requirements.txt")
	if fi, err := os.Stat(combinedReq); err == nil && !fi.IsDir() {
		s.Fetched = true
	}

	if s.Fetched {
		// Built = at least one .whl file in the versioned wheels dir.
		wheelsDir := pypiWheelsDir(d, store.Pypi)
		whlFiles, _ := filepath.Glob(filepath.Join(wheelsDir, "*.whl"))
		s.Built = len(whlFiles) > 0

		if s.Built {
			// Packaged = MANIFEST.sha256 exists.
			manifestFile := filepath.Join(wheelsDir, "MANIFEST.sha256")
			if fi, err := os.Stat(manifestFile); err == nil && !fi.IsDir() {
				s.Packaged = true
			}
		}
	}

	return s
}

// PypiArtifactDir returns the local wheels directory and S3 prefix for the
// pypi manifest. Used by the upload and sync commands.
func PypiArtifactDir(cfg *Config, store *manifest.Store) (localDir, s3Prefix string) {
	d := buildDirs(cfg.rootFor(manifest.TypePypi))
	return pypiWheelsDir(d, store.Pypi), pypiS3Prefix(store.Pypi)
}

// BuildPypi creates a build virtualenv and runs pip wheel to produce a
// directory of wheels under <build-root>/wheels[/<version>]/.
// combined-requirements.txt must already exist (produced by FetchPypi).
func BuildPypi(cfg *Config, store *manifest.Store) *Summary {
	out := cfg.stdout()
	summary := &Summary{}
	d := buildDirs(cfg.rootFor(manifest.TypePypi))

	if store.Pypi.Frozen {
		_, _ = fmt.Fprintf(out, "  [pypi] SKIPPED (frozen)\n")
		return summary
	}

	start := time.Now()
	result := Result{Type: manifest.TypePypi, Name: "wheels"}

	combinedReq := filepath.Join(cfg.rootFor(manifest.TypePypi), "combined-requirements.txt")
	if _, err := os.Stat(combinedReq); os.IsNotExist(err) {
		result.Err = fmt.Errorf("combined-requirements.txt not found at %s — run 'fetch pypi' first", combinedReq)
		summary.Failures++
		summary.Results = append(summary.Results, result)
		summary.Total++
		return summary
	}

	wheelsDir := pypiWheelsDir(d, store.Pypi)
	if err := mkdirAll(wheelsDir); err != nil {
		cfg.logf("ERROR: %v", err)
		return summary
	}

	// Create a build virtualenv.
	venvDir := filepath.Join(cfg.rootFor(manifest.TypePypi), "build-venv")
	if err := os.RemoveAll(venvDir); err != nil {
		result.Err = fmt.Errorf("remove old venv: %w", err)
		summary.Failures++
		summary.Results = append(summary.Results, result)
		summary.Total++
		return summary
	}

	_, _ = fmt.Fprintf(out, "\n>>> [pypi] build — creating virtualenv\n")
	// Try normal venv first; fall back to --without-pip if ensurepip is missing.
	if err := runCmd(out, "", "python3", "-m", "venv", venvDir); err != nil {
		_, _ = fmt.Fprintf(out, "    venv failed, retrying with --without-pip...\n")
		if err2 := runCmd(out, "", "python3", "-m", "venv", "--without-pip", venvDir); err2 != nil {
			result.Err = fmt.Errorf("python3 -m venv: %w", err2)
			summary.Failures++
			summary.Results = append(summary.Results, result)
			summary.Total++
			return summary
		}
		// Install pip into the venv manually.
		_, _ = fmt.Fprintf(out, "    Installing pip via get-pip.py...\n")
		pythonBin := filepath.Join(venvDir, "bin", "python3")
		if err3 := runCmd(out, "", "bash", "-c",
			"curl -sS https://bootstrap.pypa.io/get-pip.py | "+pythonBin); err3 != nil {
			result.Err = fmt.Errorf("install pip: %w", err3)
			summary.Failures++
			summary.Results = append(summary.Results, result)
			summary.Total++
			return summary
		}
	}

	pipBin := filepath.Join(venvDir, "bin", "pip")
	_, _ = fmt.Fprintf(out, "    Upgrading pip, wheel, setuptools...\n")
	if err := runCmd(out, "", pipBin, "install", "--upgrade", "pip", "wheel", "setuptools"); err != nil {
		result.Err = fmt.Errorf("pip upgrade: %w", err)
		summary.Failures++
		summary.Results = append(summary.Results, result)
		summary.Total++
		return summary
	}

	// Build wheels.
	_, _ = fmt.Fprintf(out, "\n>>> [pypi] build — building wheels (C extensions will compile from source)\n")
	if err := runCmd(out, "",
		pipBin, "wheel",
		"--wheel-dir", wheelsDir,
		"--progress-bar", "on",
		"-r", combinedReq,
	); err != nil {
		result.Err = fmt.Errorf("pip wheel: %w", err)
		summary.Failures++
		summary.Results = append(summary.Results, result)
		summary.Total++
		return summary
	}

	// Collect artifact paths.
	whlFiles, _ := filepath.Glob(filepath.Join(wheelsDir, "*.whl"))
	result.Artifacts = whlFiles
	result.Elapsed = time.Since(start)
	summary.Results = append(summary.Results, result)
	summary.Total++

	_, _ = fmt.Fprintf(out, "\n    Total wheels built: %d\n", len(whlFiles))
	_, _ = fmt.Fprintf(out, "    Done (%s)\n", result.Elapsed.Round(time.Millisecond))

	return summary
}

// PackagePypi generates MANIFEST.sha256 in the wheels directory. The wheels
// must already exist (produced by BuildPypi).
func PackagePypi(cfg *Config, store *manifest.Store) *Summary {
	out := cfg.stdout()
	summary := &Summary{}
	d := buildDirs(cfg.rootFor(manifest.TypePypi))

	if store.Pypi.Frozen {
		_, _ = fmt.Fprintf(out, "  [pypi] SKIPPED (frozen)\n")
		return summary
	}

	start := time.Now()
	result := Result{Type: manifest.TypePypi, Name: "manifest"}

	wheelsDir := pypiWheelsDir(d, store.Pypi)
	whlFiles, _ := filepath.Glob(filepath.Join(wheelsDir, "*.whl"))
	if len(whlFiles) == 0 {
		result.Err = fmt.Errorf("no .whl files found in %s — run 'build pypi' first", wheelsDir)
		summary.Failures++
		summary.Results = append(summary.Results, result)
		summary.Total++
		return summary
	}

	_, _ = fmt.Fprintf(out, "\n>>> [pypi] package — generating checksums\n")

	manifestFile := filepath.Join(wheelsDir, "MANIFEST.sha256")
	if err := generateWheelManifest(wheelsDir, manifestFile); err != nil {
		result.Err = fmt.Errorf("generate MANIFEST.sha256: %w", err)
		_, _ = fmt.Fprintf(out, "    ERROR: %v\n", result.Err)
		summary.Failures++
	} else {
		_, _ = fmt.Fprintf(out, "    Written: %s\n", manifestFile)
		result.Artifacts = []string{manifestFile}

		// Scan wheel metadata and persist the dependency graph. This is a
		// best-effort operation: failures are logged but do not fail the build.
		depGraphPath := filepath.Join(wheelsDir, "dep-graph.json")
		if graph, err := ScanWheelMetadata(wheelsDir, store); err != nil {
			_, _ = fmt.Fprintf(out, "    WARNING: dep-graph scan failed: %v\n", err)
		} else if err := SaveDepGraph(depGraphPath, graph); err != nil {
			_, _ = fmt.Fprintf(out, "    WARNING: dep-graph save failed: %v\n", err)
		} else {
			_, _ = fmt.Fprintf(out, "    Dep graph: %s (%d packages)\n", depGraphPath, len(graph.Packages))
		}
	}

	result.Elapsed = time.Since(start)
	summary.Results = append(summary.Results, result)
	summary.Total++
	_, _ = fmt.Fprintf(out, "    Done (%s)\n", result.Elapsed.Round(time.Millisecond))

	if cfg.Logger != nil {
		if result.Err != nil {
			cfg.Logger.Audit("FAILED  pypi/manifest  (%s)  %v", result.Elapsed.Round(time.Millisecond), result.Err)
		} else {
			cfg.Logger.Audit("OK      pypi/manifest  (%s)", result.Elapsed.Round(time.Millisecond))
		}
	}

	return summary
}

// RunPypi runs the full pypi pipeline (FetchPypi → BuildPypi → PackagePypi)
// for backward compatibility. New callers should invoke the stage functions
// individually.
func RunPypi(cfg *Config, store *manifest.Store) *Summary {
	fetchSummary := FetchPypi(cfg, store)
	if fetchSummary.HasFailures() {
		return fetchSummary
	}
	buildSummary := BuildPypi(cfg, store)
	if buildSummary.HasFailures() {
		return mergeSummaries(fetchSummary, buildSummary)
	}
	pkgSummary := PackagePypi(cfg, store)
	return mergeSummaries(mergeSummaries(fetchSummary, buildSummary), pkgSummary)
}

// generateWheelManifest writes a MANIFEST.sha256 file with checksums of every
// .whl file in wheelDir.
func generateWheelManifest(wheelDir, destPath string) error {
	matches, err := filepath.Glob(filepath.Join(wheelDir, "*.whl"))
	if err != nil {
		return err
	}

	var lines string
	for _, whl := range matches {
		sum, err := fileSHA256(whl)
		if err != nil {
			return err
		}
		lines += fmt.Sprintf("%s  %s\n", sum, filepath.Base(whl))
	}
	return os.WriteFile(destPath, []byte(lines), 0o644)
}
