package builder

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/ravinald/bodega/internal/manifest"
)

// The closure is the unit a pypi build acquires, so it is the unit bodega pins.
//
// A manifest entry names one version; pip installs everything that version
// depends on, and until the fetch resolved that closure itself the only control
// over those transitive bytes was the requirements text pip was handed. Five
// rounds of B57 went into teaching one parser to hold that line against pip's
// own, and the line kept moving. The fetch now downloads the closure, records a
// SHA-256 per file, and hands the build a directory instead of an index: there
// is nothing left for a requirements file to redirect.

// pypiSdistExts are the source-distribution suffixes an index serves. A closure
// member arrives as one whenever the distribution publishes no wheel for this
// interpreter, and it is digested and pinned exactly like a wheel.
var pypiSdistExts = []string{".tar.gz", ".zip", ".tar.bz2", ".tgz"}

// pypiArtifact is one file of a resolved closure: the bytes pip downloaded, the
// distribution and version they belong to, and the digest that must reproduce.
type pypiArtifact struct {
	File    string // basename as the index served it
	Dist    string // normalized distribution name
	Version string
	Digest  string // lowercase hex SHA-256
}

// Key returns the object key the wheels directory syncs this file under, which
// is the key a client asks for it by and the key its checksum row carries.
func (a pypiArtifact) Key() string { return manifest.PypiWheelKey(a.File) }

// pypiWheelhouseDir is where a fetch leaves the downloaded closure.
//
// It sits beside the wheels directory rather than inside it: the package stage
// syncs wheels/ wholesale, and an sdist or a superseded wheel published there
// would be served as if a build had produced it.
func pypiWheelhouseDir(root string) string { return filepath.Join(root, "wheelhouse") }

// pypiLockPath is the resolved closure the build reads instead of the manifest
// pins. Kept apart from combined-requirements.txt because that file is the
// applications' requirements as read, and this one is what they resolved to.
func pypiLockPath(root string) string { return filepath.Join(root, "resolved-requirements.txt") }

// parsePypiArtifactName splits a downloaded filename into its distribution and
// version. A wheel carries both in fixed positions; an sdist puts the version
// after the last hyphen, which is the only split PEP 625 guarantees.
func parsePypiArtifactName(base string) (dist, version string, ok bool) {
	if strings.HasSuffix(base, ".whl") {
		return parseWheelName(base)
	}
	for _, ext := range pypiSdistExts {
		stem, found := strings.CutSuffix(base, ext)
		if !found {
			continue
		}
		i := strings.LastIndex(stem, "-")
		if i <= 0 || i == len(stem)-1 {
			return "", "", false
		}
		return normalisePkgName(stem[:i]), stem[i+1:], true
	}
	return "", "", false
}

// scanPypiWheelhouse digests every distribution file in dir.
//
// A file it cannot name fails rather than being skipped: an unnamed file is one
// no lock line covers and no pin governs, and pip would still find it through
// --find-links.
func scanPypiWheelhouse(dir string) ([]pypiArtifact, error) {
	ents, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("read the wheelhouse at %s: %w", dir, err)
	}
	var arts []pypiArtifact
	for _, ent := range ents {
		if ent.IsDir() {
			continue
		}
		base := ent.Name()
		dist, version, ok := parsePypiArtifactName(base)
		if !ok {
			return nil, fmt.Errorf("%s: %s is not a distribution filename this can name, so nothing pins it", dir, base)
		}
		digest, err := computeFileSHA256(filepath.Join(dir, base))
		if err != nil {
			return nil, err
		}
		arts = append(arts, pypiArtifact{File: base, Dist: dist, Version: version, Digest: digest})
	}
	sort.Slice(arts, func(i, j int) bool { return arts[i].File < arts[j].File })
	return arts, nil
}

// pypiLockBody renders the resolved closure as a requirements file pip accepts
// under --require-hashes.
//
// It names no index and no find-links. Both reach pip on the command line,
// where a requirements file cannot replace them: pip lets a file's --index-url
// override the argument, and guards every index option with `and not no_index`,
// so --no-index on the argv is the one index control no included file can undo.
func pypiLockBody(arts []pypiArtifact) string {
	hashes := make(map[string][]string)
	var order []string
	for _, a := range arts {
		spec := a.Dist + "==" + a.Version
		if _, seen := hashes[spec]; !seen {
			order = append(order, spec)
		}
		hashes[spec] = append(hashes[spec], a.Digest)
	}
	sort.Strings(order)

	body := "# Auto-generated by bodega: the closure combined-requirements.txt resolved to.\n" +
		"# Every line is pinned and carries the digest of the bytes the fetch stored.\n"
	for _, spec := range order {
		body += spec
		for _, d := range hashes[spec] {
			body += " \\\n    --hash=sha256:" + d
		}
		body += "\n"
	}
	return body
}

// readPypiLock reads the digests back out of a lock file, keyed by the pinned
// specifier.
//
// An option line is skipped the way pip skips one when it collects install
// targets. Refusing them would put this reader back in the position B57 spent
// five rounds on — deciding acquisition by out-parsing pip — and it has nothing
// left to decide: --no-index and --find-links are on the argv, where no file
// overrides them, and --require-hashes fails any requirement an option line
// dragged in without a digest.
func readPypiLock(path string) (map[string][]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer func() { _ = f.Close() }()

	pins := make(map[string][]string)
	scanner := bufio.NewScanner(f)
	var joined string
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if rest, cont := strings.CutSuffix(line, "\\"); cont {
			joined += strings.TrimSpace(rest) + " "
			continue
		}
		joined += line
		line, joined = joined, ""
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		spec := fields[0]
		if strings.HasPrefix(spec, "-") {
			continue
		}
		if !strings.Contains(spec, "==") {
			return nil, fmt.Errorf("%s: %q is not a pinned requirement", path, spec)
		}
		for _, tok := range fields[1:] {
			digest, ok := strings.CutPrefix(tok, "--hash=sha256:")
			if !ok {
				return nil, fmt.Errorf("%s: %s carries %q, which is not a sha256 hash", path, spec, tok)
			}
			pins[spec] = append(pins[spec], digest)
		}
		if len(pins[spec]) == 0 {
			return nil, fmt.Errorf("%s: %s carries no digest, so nothing is pinned against it", path, spec)
		}
	}
	return pins, scanner.Err()
}

// verifyPypiClosure re-digests the wheelhouse against the lock before pip is
// invoked over it.
//
// --require-hashes makes pip refuse the same substitution, but pip reports it
// against whichever candidate it happened to pick and only once it gets there.
// This runs first so the build names the distribution, the digest on record and
// the digest on disk, which is what somebody reads at 03:00.
func verifyPypiClosure(lockPath, house string) error {
	want, err := readPypiLock(lockPath)
	if err != nil {
		return err
	}
	arts, err := scanPypiWheelhouse(house)
	if err != nil {
		return err
	}

	seen := make(map[string]bool, len(want))
	for _, a := range arts {
		spec := a.Dist + "==" + a.Version
		recorded, ok := want[spec]
		if !ok {
			return fmt.Errorf("pypi %s: %s holds %s, which %s pins nothing against — the build would acquire bytes nobody recorded",
				a.Dist, house, a.File, filepath.Base(lockPath))
		}
		if !slices.Contains(recorded, a.Digest) {
			return fmt.Errorf("pypi %s==%s: %s no longer matches the digest recorded at fetch: recorded=%s received=%s",
				a.Dist, a.Version, a.File, strings.Join(recorded, ","), a.Digest)
		}
		seen[spec] = true
	}
	missing := make([]string, 0, len(want))
	for spec := range want {
		if !seen[spec] {
			missing = append(missing, spec)
		}
	}
	if len(missing) > 0 {
		sort.Strings(missing)
		return fmt.Errorf("pypi: %s pins %s and %s holds no file for them — re-run 'fetch pypi'",
			filepath.Base(lockPath), strings.Join(missing, ", "), house)
	}
	return nil
}

// pypiVenvDir is the build environment both stages run pip out of.
func pypiVenvDir(root string) string { return filepath.Join(root, "build-venv") }

// ensurePypiVenv returns the pip the pypi stages run, building the venv when
// fresh is set or when what is there has no pip.
//
// One venv for both stages, because the alternative is a second pip: the fetch
// would otherwise need `python3 -m pip` on the host as well as ensurepip, and
// the two would be different versions resolving and consuming one closure.
//
// There is no --without-pip fallback. It bootstrapped pip by piping
// bootstrap.pypa.io/get-pip.py into the interpreter, which is an origin outside
// every control these stages apply and nothing verified the bytes. A host whose
// python cannot build a venv with pip is a host to fix.
func ensurePypiVenv(out io.Writer, root string, fresh bool) (string, error) {
	venv := pypiVenvDir(root)
	pipBin := filepath.Join(venv, "bin", "pip")
	if !fresh {
		if _, err := os.Stat(pipBin); err == nil {
			return pipBin, nil
		}
	} else if err := os.RemoveAll(venv); err != nil {
		return "", fmt.Errorf("remove old venv: %w", err)
	}

	_, _ = fmt.Fprintf(out, "    Creating the build virtualenv at %s\n", venv)
	if err := runCmdEnv(out, "", pypiPipEnv(), "python3", "-m", "venv", venv); err != nil {
		return "", fmt.Errorf("python3 -m venv %s: %w — install the platform's python3-venv (ensurepip) package", venv, err)
	}
	if _, err := os.Stat(pipBin); err != nil {
		return "", fmt.Errorf("%s built no pip — install the platform's python3-venv (ensurepip) package", venv)
	}
	return pipBin, nil
}

// downloadPypiClosure resolves and downloads everything combined-requirements.txt
// implies, into a wheelhouse this instance owns.
//
// The wheelhouse is emptied first. pip reuses a file already present in --dest
// without asking the index, so a second fetch over a populated directory would
// report the first fetch's bytes and the substitution this exists to catch would
// never reach a digest.
func downloadPypiClosure(out io.Writer, pipBin, indexURL, combinedReq, house string) ([]pypiArtifact, error) {
	if err := os.RemoveAll(house); err != nil {
		return nil, fmt.Errorf("clear the wheelhouse at %s: %w", house, err)
	}
	if err := mkdirAll(house); err != nil {
		return nil, err
	}

	if err := runCmdEnv(out, "", pypiPipEnv(), pipBin, "download",
		"--isolated", "--no-cache-dir", "--disable-pip-version-check",
		"--index-url", indexURL,
		"--dest", house,
		"-r", combinedReq,
	); err != nil {
		return nil, fmt.Errorf("pip download: %w", err)
	}

	arts, err := scanPypiWheelhouse(house)
	if err != nil {
		return nil, err
	}

	// A source distribution is built at build time, and pip assembles its build
	// environment through the same finder the build runs under. With --no-index
	// that finder reaches only the wheelhouse, so the default PEP 518 backend
	// has to be in it or every sdist in the closure fails to build. A backend
	// other than setuptools is named as a pypi manifest entry, which puts it in
	// the closure like anything else.
	if slices.ContainsFunc(arts, func(a pypiArtifact) bool { return !strings.HasSuffix(a.File, ".whl") }) {
		_, _ = fmt.Fprintf(out, "    Closure holds a source distribution; adding the default build backend\n")
		if err := runCmdEnv(out, "", pypiPipEnv(), pipBin, "download",
			"--isolated", "--no-cache-dir", "--disable-pip-version-check",
			"--only-binary", ":all:",
			"--index-url", indexURL,
			"--dest", house,
			"setuptools", "wheel",
		); err != nil {
			return nil, fmt.Errorf("pip download of the build backend: %w", err)
		}
		if arts, err = scanPypiWheelhouse(house); err != nil {
			return nil, err
		}
	}
	return arts, nil
}

// pinPypiClosure records one checksum row per closure artifact and refuses a
// version whose bytes changed.
//
// The row is the same row every other type writes and `bodega pkg checksum list`
// reads: same table, same source word, keyed by the object key the wheel is
// served under. What differs is only where the key comes from, because a pypi
// manifest entry covers a closure rather than a file.
func (c *Config) pinPypiClosure(ctx context.Context, arts []pypiArtifact, house string) error {
	for _, a := range arts {
		cs := newSHA256Checksum(a.Digest)
		if err := c.pinArtifactDigest(ctx, a.Key(), manifest.TypePypi, a.Dist, a.Version, cs); err != nil {
			// Refused rather than stored: the bytes go before the error does,
			// so a later build cannot reach them through --find-links.
			_ = os.Remove(filepath.Join(house, a.File))
			return err
		}
	}
	return nil
}
